version: 2.1
description: "Docker utils"

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0

commands:
  publish-ecr:
    description: "Publish to Compute's ECR repo."
    parameters:
      repository:
        type: string
        default: "734247230719.dkr.ecr.us-west-2.amazonaws.com"
      image:
        type: string
        default: compute/$CIRCLE_PROJECT_REPONAME
      dockerfile:
        type: string
        default: Dockerfile
      path:
        type: string
        default: .
      extra-build-args:
        type: string
        default: ''
    steps:
      - aws-ecr/build-and-push-image:
          account-url: <<parameters.repository>>
          create-repo: true
          dockerfile: <<parameters.dockerfile>>
          path: <<parameters.path>>
          repo: <<parameters.image>>
          tag: sha-$CIRCLE_SHA1
          extra-build-args: <<parameters.image>>