version: 2.1
description: "Docker utils"

orbs:
  circleci-cli: circleci/circleci-cli@0.0.1
  aws-cli: circleci/aws-cli@0.1.9

commands:
  publish-ecr:
    description: "Publish to Compute's ECR repo."
    parameters:
      repository:
        type: string
        default: "734247230719.dkr.ecr.us-west-2.amazonaws.com"
      image:
        type: string
        default: compute/$CIRCLE_PROJECT_REPONAME
      dockerfile:
        type: string
        default: Dockerfile
      path:
        type: string
        default: .
      extra-build-args:
        type: string
        default: ''
    steps:
      - run:
          name: Build image <<parameters.image>>
          command: |
            docker build \
            <<#parameters.extra-build-args>><<parameters.extra-build-args>><</parameters.extra-build-args>> \
            -t <<parameters.image>> <<parameters.path>>

            docker tag <<parameters.image>>:latest <<parameters.repository>>/<<parameters.image>>:sha-$CIRCLE_SHA1
            docker tag <<parameters.image>>:latest <<parameters.repository>>/<<parameters.image>>:branch-$CIRCLE_BRANCH
      - aws-cli/install
      - run:
          name: Publish image <<parameters.image>>
          command: |
            eval $(aws ecr get-login --no-include-email --region us-west-2)
            docker push <<parameters.repository>>/<<parameters.image>>:sha-$CIRCLE_SHA1
            docker push <<parameters.repository>>/<<parameters.image>>:branch-$CIRCLE_BRANCH