version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - validate-orbs
      - publish-orbs:
          requires:
            - validate-orbs
          filters:
            branches:
              only: master


orbs:
  circleci-cli: compute/circleci@0.0.3

jobs:
  validate-orbs:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394
    steps:
      - checkout
      - circleci-cli/install:
          token: CIRCLECI_API_TOKEN
      - run: clojure -m validate-orbs

  publish-orbs:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394
    steps:
      - checkout
      - circleci-cli/install:
          token: CIRCLECI_API_TOKEN
      - run: clojure -m publish-orbs